name: Community Management
on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, merged, reopened]

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  manage-community:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome new contributors
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const isFirstTimeContributor = pr.author_association === 'FIRST_TIME_CONTRIBUTOR';
            
            if (isFirstTimeContributor) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## 🎉 Welcome to RepoCraft!
                
                Thank you for your first contribution to RepoCraft! We're excited to have you join our community.
                
                ### What happens next?
                1. **Review** - Our team will review your changes
                2. **Feedback** - We may request some adjustments
                3. **Merge** - Once approved, your changes will be merged
                4. **Celebration** - You'll be added to our contributors list! 🎊
                
                ### Resources
                - [Contributing Guide](https://github.com/AnLoMinus/RepoCraft/blob/main/CONTRIBUTING.md)
                - [Style Guide](https://github.com/AnLoMinus/RepoCraft/blob/main/docs/STYLE_GUIDE.md)
                - [Community Guidelines](https://github.com/AnLoMinus/RepoCraft/blob/main/CODE_OF_CONDUCT.md)
                
                ### Questions?
                Feel free to ask questions in the [Discussions](https://github.com/AnLoMinus/RepoCraft/discussions) section.
                
                Welcome aboard! 🚀`
              });
            }

      - name: Thank contributors
        if: github.event_name == 'pull_request' && github.event.action == 'merged'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const contributor = pr.user.login;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 🎉 Thank you, @${contributor}!
              
              Your contribution has been merged! 🚀
              
              ### What you contributed:
              - **Title:** ${pr.title}
              - **Files changed:** ${pr.changed_files}
              - **Additions:** +${pr.additions}
              - **Deletions:** -${pr.deletions}
              
              ### Impact
              Your changes will help improve RepoCraft for the entire community. Thank you for making a difference! 🙏
              
              ### Next steps
              - You'll be added to our [Contributors](https://github.com/AnLoMinus/RepoCraft/blob/main/CONTRIBUTORS.md) list
              - Consider joining our [Discord community](https://discord.gg/repocraft)
              - Follow us for updates on new features and releases
              
              Keep up the great work! 💪`
            });

      - name: Handle issue closure
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            
            // Check if it's a bug that was fixed
            if (labels.includes('bug')) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## ✅ Bug Fixed
                
                This bug has been resolved! Thank you for reporting it and helping us improve RepoCraft.
                
                ### What was fixed:
                - **Issue:** ${issue.title}
                - **Resolution:** ${issue.state_reason || 'Fixed'}
                - **Date:** ${new Date().toISOString()}
                
                ### Impact
                Your bug report helped us identify and fix an issue that could have affected other users. We appreciate your contribution to making RepoCraft better! 🙏
                
                ### Stay updated
                - Follow our [releases](https://github.com/AnLoMinus/RepoCraft/releases) for updates
                - Join our [Discord community](https://discord.gg/repocraft) for discussions
                - Star ⭐ our repository to stay updated
                
                Thank you for helping us improve! 🎉`
              });
            }
            
            // Check if it's a feature request that was implemented
            if (labels.includes('enhancement')) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## 🎉 Feature Implemented
                
                Your feature request has been implemented! Thank you for the great suggestion.
                
                ### What was added:
                - **Feature:** ${issue.title}
                - **Status:** Implemented
                - **Date:** ${new Date().toISOString()}
                
                ### Impact
                Your feature request helped us understand what the community needs. We're excited to see how this new feature will help users! 🚀
                
                ### Try it out
                - Check out the latest [release](https://github.com/AnLoMinus/RepoCraft/releases)
                - Read the [documentation](https://github.com/AnLoMinus/RepoCraft/blob/main/docs/GETTING_STARTED.md)
                - Share your feedback in [Discussions](https://github.com/AnLoMinus/RepoCraft/discussions)
                
                Thank you for the great idea! 💡`
              });
            }

      - name: Create community highlights
        if: github.event_name == 'pull_request' && github.event.action == 'merged'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const contributor = pr.user.login;
            const isFirstTimeContributor = pr.author_association === 'FIRST_TIME_CONTRIBUTOR';
            
            if (isFirstTimeContributor) {
              // Create a community highlight discussion
              await github.rest.discussions.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🌟 Community Highlight: Welcome @${contributor}!`,
                body: `## 🌟 Community Highlight
                
                We're excited to welcome @${contributor} to the RepoCraft community! 🎉
                
                ### First Contribution
                - **PR:** ${pr.title}
                - **Files changed:** ${pr.changed_files}
                - **Additions:** +${pr.additions}
                - **Deletions:** -${pr.deletions}
                
                ### Impact
                This contribution helps improve RepoCraft for everyone. Thank you for joining our mission to make GitHub repositories better! 🙏
                
                ### Welcome to the community!
                - Join our [Discord server](https://discord.gg/repocraft) for real-time discussions
                - Follow our [releases](https://github.com/AnLoMinus/RepoCraft/releases) for updates
                - Star ⭐ our repository to show your support
                
                We're thrilled to have you as part of the RepoCraft family! 🚀`,
                category: "General"
              });
            }

      - name: Update contributors list
        if: github.event_name == 'pull_request' && github.event.action == 'merged'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const contributor = pr.user.login;
            const contributorName = pr.user.name || contributor;
            const contributorUrl = pr.user.html_url;
            
            // This would typically update a contributors file
            // For now, we'll create a comment with the information
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 📝 Contributor Update
              
              @${contributor} has been added to our contributors list!
              
              ### Contributor Details
              - **Name:** ${contributorName}
              - **GitHub:** [@${contributor}](${contributorUrl})
              - **Contribution:** ${pr.title}
              - **Date:** ${new Date().toISOString()}
              
              Thank you for contributing to RepoCraft! 🙏`
            });
