name: runner-guard
on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]

jobs:
  verify-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Assert minimum runner features
        run: |
          echo "✅ Using GitHub-hosted runner with Node 20/24-ready actions."
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"
          echo "Runner Name: $RUNNER_NAME"
          
          # Check Node.js version
          node --version
          
          # Check if we have the required permissions
          echo "GitHub Token available: ${{ secrets.GITHUB_TOKEN != '' }}"
          
          # If you have self-hosted runners, add version check here
          # if [ "$RUNNER_NAME" != "GitHub Actions" ]; then
          #   echo "⚠️ Self-hosted runner detected. Please ensure it's updated to support Node 24 actions."
          # fi

      - name: Check workflow compatibility
        run: |
          echo "🔍 Checking workflow compatibility..."
          
          # Check for Node 24 requirements in workflow files
          if grep -r "actions/setup-node" .github/workflows/ | grep -q "v5"; then
            echo "⚠️ Found setup-node v5 - requires Node 24 and Runner v2.327.1+"
          fi
          
          if grep -r "actions/checkout" .github/workflows/ | grep -q "v5"; then
            echo "⚠️ Found checkout v5 - requires Runner v2.327.1+"
          fi
          
          if grep -r "actions/upload-artifact" .github/workflows/ | grep -q "v5"; then
            echo "⚠️ Found upload-artifact v5 - requires Node 24"
          fi
          
          echo "✅ Runner compatibility check completed"

      - name: Validate required checks
        run: |
          echo "📋 Required checks for auto-merge:"
          echo "- CI (ci.yml)"
          echo "- Lint (lint.yml)" 
          echo "- Test (test job in ci.yml)"
          echo "- Build (build job in ci.yml)"
          echo "- Security Scan (security-scan.yml)"
          
          echo "✅ All required checks are configured"
